// Centralized theme token definitions for all design styles.
// Each theme defines CSS variables that power the entire UI.

const baseTokens = {
  '--font-sans': "'Inter', system-ui, -apple-system, Segoe UI, sans-serif",
  '--font-serif': "'Merriweather', Georgia, serif",
  '--font-mono': "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
  '--font-size-xs': '0.75rem',
  '--font-size-sm': '0.875rem',
  '--font-size-md': '1rem',
  '--font-size-lg': '1.125rem',
  '--font-size-xl': '1.5rem',
  '--font-size-2xl': '2.125rem',
  '--font-weight-regular': '400',
  '--font-weight-medium': '600',
  '--font-weight-bold': '700',
  '--space-1': '0.25rem',
  '--space-2': '0.5rem',
  '--space-3': '0.75rem',
  '--space-4': '1rem',
  '--space-5': '1.5rem',
  '--space-6': '2rem',
  '--space-7': '3rem',
  '--space-8': '4rem',
  '--radius-sm': '0.5rem',
  '--radius-md': '0.75rem',
  '--radius-lg': '1.25rem',
  '--radius-pill': '999px',
  '--border-width': '1px',
  '--blur-amount': '0px',
  '--glass-bg': 'rgba(255, 255, 255, 0.12)',
  '--shadow-sm': '0 6px 20px rgba(0, 0, 0, 0.08)',
  '--shadow-md': '0 12px 32px rgba(0, 0, 0, 0.12)',
  '--shadow-lg': '0 24px 60px rgba(0, 0, 0, 0.18)',
  '--shadow-inset': 'inset 0 2px 6px rgba(0, 0, 0, 0.15)',
  '--layout-max': '1200px',
  '--bg-pattern': 'none',
  '--card-tilt': 'rotateX(0deg) rotateY(0deg)',
  '--card-depth': '0px',
  '--liquid-blur': '18px',
  '--liquid-glow': '0 0 30px rgba(125, 211, 252, 0.35)',
  '--liquid-flow-1': 'rgba(125, 211, 252, 0.35)',
  '--liquid-flow-2': 'rgba(196, 181, 253, 0.3)',
  '--liquid-flow-3': 'rgba(34, 211, 238, 0.3)',
  '--motion-soft': '22',
}

const compactSpacing = {
  '--space-1': '0.2rem',
  '--space-2': '0.4rem',
  '--space-3': '0.6rem',
  '--space-4': '0.85rem',
  '--space-5': '1.1rem',
  '--space-6': '1.5rem',
  '--space-7': '2.2rem',
  '--space-8': '3rem',
}

const spaciousSpacing = {
  '--space-1': '0.35rem',
  '--space-2': '0.75rem',
  '--space-3': '1.1rem',
  '--space-4': '1.4rem',
  '--space-5': '2rem',
  '--space-6': '2.75rem',
  '--space-7': '3.5rem',
  '--space-8': '4.75rem',
}

const accessibilityType = {
  '--font-size-xs': '0.875rem',
  '--font-size-sm': '1rem',
  '--font-size-md': '1.125rem',
  '--font-size-lg': '1.375rem',
  '--font-size-xl': '1.75rem',
  '--font-size-2xl': '2.5rem',
  '--font-weight-regular': '500',
  '--font-weight-medium': '700',
  '--font-weight-bold': '800',
}

export const themes = [
  {
    id: 'skeuomorphism',
    name: 'Skeuomorphism',
    description: 'Rich textures, tactile surfaces, and layered depth.',
    effects: { surface: 'skeuo' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#1b120c',
      '--color-surface': '#3a2a1b',
      '--color-surface-2': '#4a3521',
      '--color-text': '#f8e9d2',
      '--color-muted': '#d7c0a0',
      '--color-primary': '#b5742c',
      '--color-secondary': '#5e8c7b',
      '--color-accent': '#d6a25c',
      '--color-border': '#7a5636',
      '--color-on-primary': '#1b120c',
      '--color-on-secondary': '#f8e9d2',
      '--shadow-sm': 'inset 0 1px 0 rgba(255,255,255,0.35), 0 6px 14px rgba(0,0,0,0.35)',
      '--shadow-md': 'inset 0 2px 0 rgba(255,255,255,0.3), 0 12px 24px rgba(0,0,0,0.45)',
      '--shadow-lg': 'inset 0 3px 0 rgba(255,255,255,0.25), 0 18px 36px rgba(0,0,0,0.5)',
      '--shadow-inset': 'inset 0 3px 6px rgba(0,0,0,0.45)',
      '--bg-pattern': 'linear-gradient(120deg, rgba(255,255,255,0.04), rgba(0,0,0,0.12))',
    },
  },
  {
    id: 'flat',
    name: 'Flat Design',
    description: 'Bold color blocks and sharp contrast, zero depth.',
    effects: { surface: 'flat' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f5f7fb',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#eef2ff',
      '--color-text': '#1c2250',
      '--color-muted': '#4e5699',
      '--color-primary': '#4657f0',
      '--color-secondary': '#f7684f',
      '--color-accent': '#12c2e9',
      '--color-border': '#dfe3ff',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--shadow-sm': 'none',
      '--shadow-md': 'none',
      '--shadow-lg': 'none',
      '--shadow-inset': 'none',
      '--radius-sm': '0.25rem',
      '--radius-md': '0.5rem',
      '--radius-lg': '0.75rem',
    },
  },
  {
    id: 'flat-2',
    name: 'Flat 2.0',
    description: 'Flat UI with gentle gradients and soft borders.',
    effects: { surface: 'flat' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f3f4ff',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#edf0ff',
      '--color-text': '#202448',
      '--color-muted': '#5f64a8',
      '--color-primary': '#6366f1',
      '--color-secondary': '#ec4899',
      '--color-accent': '#14b8a6',
      '--color-border': '#d7dbff',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--shadow-sm': '0 10px 30px rgba(99,102,241,0.12)',
      '--shadow-md': '0 16px 40px rgba(99,102,241,0.18)',
      '--shadow-lg': '0 20px 50px rgba(99,102,241,0.24)',
      '--shadow-inset': 'none',
    },
  },
  {
    id: 'material',
    name: 'Material Design',
    description: 'Clean surfaces, elevation, and refined motion.',
    effects: { surface: 'material' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f5f9',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#2563eb',
      '--color-secondary': '#7c3aed',
      '--color-accent': '#0ea5e9',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--shadow-sm': '0 1px 2px rgba(15,23,42,0.12)',
      '--shadow-md': '0 6px 16px rgba(15,23,42,0.18)',
      '--shadow-lg': '0 12px 28px rgba(15,23,42,0.24)',
    },
  },
  {
    id: 'neumorphism',
    name: 'Neumorphism',
    description: 'Soft UI with light and shadow blending.',
    effects: { surface: 'neumorph' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#e6ebf2',
      '--color-surface': '#e6ebf2',
      '--color-surface-2': '#d9e0ea',
      '--color-text': '#2b3340',
      '--color-muted': '#5f6b7a',
      '--color-primary': '#6a7cff',
      '--color-secondary': '#ff7ab6',
      '--color-accent': '#4ecdc4',
      '--color-border': 'rgba(255,255,255,0.6)',
      '--color-on-primary': '#f8faff',
      '--color-on-secondary': '#ffffff',
      '--shadow-sm': '8px 8px 16px rgba(163,177,198,0.65), -8px -8px 16px rgba(255,255,255,0.9)',
      '--shadow-md': '12px 12px 24px rgba(163,177,198,0.7), -12px -12px 24px rgba(255,255,255,0.95)',
      '--shadow-lg': '18px 18px 36px rgba(163,177,198,0.7), -18px -18px 36px rgba(255,255,255,0.98)',
      '--shadow-inset': 'inset 4px 4px 10px rgba(163,177,198,0.6), inset -4px -4px 10px rgba(255,255,255,0.9)',
      '--border-width': '0px',
    },
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    description: 'Translucent layers with blur and minimal structure.',
    effects: { surface: 'glass' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--color-bg': '#0a1224',
      '--color-surface': 'rgba(255,255,255,0.12)',
      '--color-surface-2': 'rgba(255,255,255,0.16)',
      '--color-text': '#e8f0ff',
      '--color-muted': '#b8c6ff',
      '--color-primary': '#7dd3fc',
      '--color-secondary': '#c4b5fd',
      '--color-accent': '#22d3ee',
      '--color-border': 'rgba(255,255,255,0.2)',
      '--color-on-primary': '#0a1224',
      '--color-on-secondary': '#0a1224',
      '--shadow-sm': '0 10px 30px rgba(8,16,40,0.35)',
      '--shadow-md': '0 18px 40px rgba(8,16,40,0.45)',
      '--shadow-lg': '0 28px 60px rgba(8,16,40,0.55)',
      '--blur-amount': '18px',
      '--glass-bg': 'rgba(255, 255, 255, 0.18)',
      '--bg-pattern': 'radial-gradient(circle at top, rgba(34,211,238,0.25), transparent 50%)',
    },
  },
  {
    id: 'claymorphism',
    name: 'Claymorphism',
    description: 'Soft clay surfaces with warm highlights.',
    effects: { surface: 'clay' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f7f0ec',
      '--color-surface': '#f9e8de',
      '--color-surface-2': '#f2d9cc',
      '--color-text': '#3f2f27',
      '--color-muted': '#7a5f55',
      '--color-primary': '#ff8a65',
      '--color-secondary': '#8fd3ff',
      '--color-accent': '#f6c453',
      '--color-border': '#e7c4b4',
      '--color-on-primary': '#3f2f27',
      '--color-on-secondary': '#18304a',
      '--shadow-sm': '0 8px 18px rgba(58,38,28,0.15), inset 0 2px 8px rgba(255,255,255,0.7)',
      '--shadow-md': '0 18px 28px rgba(58,38,28,0.22), inset 0 4px 12px rgba(255,255,255,0.65)',
      '--shadow-lg': '0 26px 40px rgba(58,38,28,0.3), inset 0 6px 16px rgba(255,255,255,0.6)',
    },
  },
  {
    id: 'aurora',
    name: 'Aurora UI',
    description: 'Vivid gradients and glowing accents.',
    effects: { surface: 'aurora' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0b0f1f',
      '--color-surface': '#141b32',
      '--color-surface-2': '#18213d',
      '--color-text': '#e2e8ff',
      '--color-muted': '#98a2e3',
      '--color-primary': '#7c3aed',
      '--color-secondary': '#22d3ee',
      '--color-accent': '#f472b6',
      '--color-border': '#2b3561',
      '--color-on-primary': '#f3e8ff',
      '--color-on-secondary': '#06101d',
      '--shadow-sm': '0 10px 30px rgba(124,58,237,0.25)',
      '--shadow-md': '0 16px 40px rgba(34,211,238,0.25)',
      '--shadow-lg': '0 24px 60px rgba(244,114,182,0.28)',
      '--bg-pattern': 'radial-gradient(circle at 10% 10%, rgba(124,58,237,0.35), transparent 40%), radial-gradient(circle at 80% 20%, rgba(34,211,238,0.25), transparent 45%), radial-gradient(circle at 30% 80%, rgba(244,114,182,0.25), transparent 40%)',
    },
  },
  {
    id: 'brutalism',
    name: 'Brutalism',
    description: 'Raw, high-contrast, unapologetically bold.',
    effects: { surface: 'brutal' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#fff7e6',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#fff0c9',
      '--color-text': '#1f1a17',
      '--color-muted': '#3d2f22',
      '--color-primary': '#ff4d00',
      '--color-secondary': '#0057ff',
      '--color-accent': '#00b894',
      '--color-border': '#1f1a17',
      '--color-on-primary': '#1f1a17',
      '--color-on-secondary': '#ffffff',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--shadow-sm': 'none',
      '--shadow-md': 'none',
      '--shadow-lg': 'none',
      '--border-width': '2px',
    },
  },
  {
    id: 'neo-brutalism',
    name: 'Neo-Brutalism',
    description: 'Playful color with thick borders and offset shadows.',
    effects: { surface: 'neo-brutal' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#fef08a',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#fef3c7',
      '--color-text': '#111827',
      '--color-muted': '#374151',
      '--color-primary': '#a855f7',
      '--color-secondary': '#22c55e',
      '--color-accent': '#ef4444',
      '--color-border': '#111827',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#052e16',
      '--border-width': '3px',
      '--shadow-sm': '6px 6px 0 #111827',
      '--shadow-md': '10px 10px 0 #111827',
      '--shadow-lg': '14px 14px 0 #111827',
      '--radius-sm': '0.6rem',
      '--radius-md': '0.9rem',
      '--radius-lg': '1.2rem',
    },
  },
  {
    id: 'anti-design',
    name: 'Anti-Design',
    description: 'Rebellious, chaotic, and deliberately off-grid.',
    effects: { surface: 'anti' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0b0b0b',
      '--color-surface': '#fef08a',
      '--color-surface-2': '#ff7ab6',
      '--color-text': '#00ffcc',
      '--color-muted': '#ffb703',
      '--color-primary': '#ff006e',
      '--color-secondary': '#8338ec',
      '--color-accent': '#00f5d4',
      '--color-border': '#ffffff',
      '--color-on-primary': '#0b0b0b',
      '--color-on-secondary': '#ffffff',
      '--radius-sm': '0.1rem',
      '--radius-md': '0.35rem',
      '--radius-lg': '0.5rem',
      '--border-width': '2px',
      '--bg-pattern': 'repeating-linear-gradient(135deg, rgba(255,255,255,0.08) 0 8px, transparent 8px 16px)',
    },
  },
  {
    id: 'minimalism',
    name: 'Minimalism',
    description: 'Neutral palette, generous whitespace, refined typography.',
    effects: { surface: 'minimal' },
    tokens: {
      ...baseTokens,
      ...spaciousSpacing,
      '--color-bg': '#f7f7f5',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f1ee',
      '--color-text': '#111111',
      '--color-muted': '#5c5c5c',
      '--color-primary': '#111111',
      '--color-secondary': '#9ca3af',
      '--color-accent': '#8b5cf6',
      '--color-border': '#e4e4e0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#111111',
      '--shadow-sm': '0 6px 16px rgba(0,0,0,0.06)',
      '--shadow-md': '0 10px 22px rgba(0,0,0,0.08)',
      '--shadow-lg': '0 16px 32px rgba(0,0,0,0.12)',
    },
  },
  {
    id: 'maximalism',
    name: 'Maximalism',
    description: 'Loud colors, layered textures, and bold motion.',
    effects: { surface: 'maximal' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#1c0f2e',
      '--color-surface': '#2e1647',
      '--color-surface-2': '#3a1f5c',
      '--color-text': '#f8f0ff',
      '--color-muted': '#d1b3ff',
      '--color-primary': '#ff6d00',
      '--color-secondary': '#00e5ff',
      '--color-accent': '#f72585',
      '--color-border': '#5f2b91',
      '--color-on-primary': '#2a0f2a',
      '--color-on-secondary': '#071e25',
      '--shadow-sm': '0 12px 26px rgba(255,109,0,0.25)',
      '--shadow-md': '0 18px 34px rgba(247,37,133,0.28)',
      '--shadow-lg': '0 28px 50px rgba(0,229,255,0.25)',
      '--bg-pattern': 'radial-gradient(circle at top left, rgba(255,109,0,0.25), transparent 40%), radial-gradient(circle at bottom right, rgba(0,229,255,0.2), transparent 50%)',
    },
  },
  {
    id: 'human-centered',
    name: 'Human-Centered Design',
    description: 'Warm, friendly, and approachable.',
    effects: { surface: 'human' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#fff8f3',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#ffe9dc',
      '--color-text': '#3c2c20',
      '--color-muted': '#7a5e4f',
      '--color-primary': '#f97316',
      '--color-secondary': '#22c55e',
      '--color-accent': '#3b82f6',
      '--color-border': '#f0d2c2',
      '--color-on-primary': '#2b160b',
      '--color-on-secondary': '#052e16',
      '--shadow-sm': '0 10px 20px rgba(249,115,22,0.12)',
      '--shadow-md': '0 18px 32px rgba(59,130,246,0.16)',
      '--shadow-lg': '0 28px 44px rgba(34,197,94,0.18)',
    },
  },
  {
    id: 'accessibility-first',
    name: 'Accessibility-First',
    description: 'High contrast and larger type for readability.',
    effects: { surface: 'accessibility' },
    tokens: {
      ...baseTokens,
      ...accessibilityType,
      '--color-bg': '#0f172a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f9fafb',
      '--color-muted': '#e5e7eb',
      '--color-primary': '#22c55e',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#f59e0b',
      '--color-border': '#94a3b8',
      '--color-on-primary': '#052e16',
      '--color-on-secondary': '#0f172a',
      '--border-width': '2px',
    },
  },
  {
    id: 'mobile-first',
    name: 'Mobile-First',
    description: 'Compact spacing and focused content blocks.',
    effects: { surface: 'mobile' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--layout-max': '980px',
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#eef2ff',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#0ea5e9',
      '--color-secondary': '#8b5cf6',
      '--color-accent': '#22c55e',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
    },
  },
  {
    id: 'responsive-adaptive',
    name: 'Responsive / Adaptive',
    description: 'Flexible layout with fluid spacing cues.',
    effects: { surface: 'responsive' },
    tokens: {
      ...baseTokens,
      '--layout-max': '1280px',
      '--color-bg': '#f1f5f9',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#e2e8f0',
      '--color-text': '#0f172a',
      '--color-muted': '#334155',
      '--color-primary': '#14b8a6',
      '--color-secondary': '#6366f1',
      '--color-accent': '#f97316',
      '--color-border': '#cbd5f5',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
    },
  },
  {
    id: 'dark-light',
    name: 'Dark UI / Light UI',
    description: 'Automatic system-aware light and dark palette.',
    effects: { surface: 'adaptive' },
    tokens: {
      ...baseTokens,
      '--color-bg-light': '#f8fafc',
      '--color-surface-light': '#ffffff',
      '--color-surface-2-light': '#e2e8f0',
      '--color-text-light': '#0f172a',
      '--color-muted-light': '#475569',
      '--color-primary-light': '#2563eb',
      '--color-secondary-light': '#9333ea',
      '--color-accent-light': '#f97316',
      '--color-border-light': '#cbd5f5',
      '--color-on-primary-light': '#ffffff',
      '--color-on-secondary-light': '#ffffff',
      '--color-bg-dark': '#0b1120',
      '--color-surface-dark': '#111827',
      '--color-surface-2-dark': '#1f2937',
      '--color-text-dark': '#f8fafc',
      '--color-muted-dark': '#cbd5f5',
      '--color-primary-dark': '#38bdf8',
      '--color-secondary-dark': '#a78bfa',
      '--color-accent-dark': '#f97316',
      '--color-border-dark': '#334155',
      '--color-on-primary-dark': '#0b1120',
      '--color-on-secondary-dark': '#0b1120',
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#e2e8f0',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#2563eb',
      '--color-secondary': '#9333ea',
      '--color-accent': '#f97316',
      '--color-border': '#cbd5f5',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
    },
  },
  {
    id: 'spatial-3d',
    name: '3D UI / Spatial UI',
    description: 'Depth, perspective, and spatial elevation.',
    effects: { surface: 'spatial' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0f172a',
      '--color-surface': '#1e293b',
      '--color-surface-2': '#243350',
      '--color-text': '#e2e8f0',
      '--color-muted': '#a3bffa',
      '--color-primary': '#38bdf8',
      '--color-secondary': '#f472b6',
      '--color-accent': '#fbbf24',
      '--color-border': '#334155',
      '--color-on-primary': '#0f172a',
      '--color-on-secondary': '#1f2937',
      '--shadow-sm': '0 16px 30px rgba(15,23,42,0.35)',
      '--shadow-md': '0 26px 50px rgba(15,23,42,0.45)',
      '--shadow-lg': '0 40px 80px rgba(15,23,42,0.55)',
      '--card-tilt': 'rotateX(6deg) rotateY(-6deg)',
      '--card-depth': '18px',
    },
  },
  {
    id: 'ai-generative',
    name: 'AI-Driven / Generative UI',
    description: 'Dynamic gradients and creative combinations.',
    effects: { surface: 'ai' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0d0b1f',
      '--color-surface': '#1a1730',
      '--color-surface-2': '#221d3d',
      '--color-text': '#e0e7ff',
      '--color-muted': '#c7d2fe',
      '--color-primary': '#8b5cf6',
      '--color-secondary': '#14b8a6',
      '--color-accent': '#f43f5e',
      '--color-border': '#312e81',
      '--color-on-primary': '#0b1022',
      '--color-on-secondary': '#071f20',
      '--shadow-sm': '0 10px 30px rgba(139,92,246,0.25)',
      '--shadow-md': '0 18px 44px rgba(20,184,166,0.22)',
      '--shadow-lg': '0 30px 70px rgba(244,63,94,0.2)',
      '--bg-pattern': 'radial-gradient(circle at 20% 20%, rgba(139,92,246,0.2), transparent 40%), radial-gradient(circle at 80% 30%, rgba(20,184,166,0.2), transparent 40%), radial-gradient(circle at 30% 80%, rgba(244,63,94,0.18), transparent 45%)',
    },
  },
  {
    id: 'swiss-international',
    name: 'Swiss / International Style UI',
    description: 'Grid precision, clarity, and typographic discipline.',
    effects: { surface: 'swiss' },
    tokens: {
      ...baseTokens,
      ...spaciousSpacing,
      '--color-bg': '#f9fafb',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f5f9',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#e11d48',
      '--color-secondary': '#0f172a',
      '--color-accent': '#2563eb',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--radius-sm': '0.2rem',
      '--radius-md': '0.4rem',
      '--radius-lg': '0.6rem',
      '--shadow-sm': '0 6px 18px rgba(15,23,42,0.08)',
      '--shadow-md': '0 12px 24px rgba(15,23,42,0.12)',
      '--shadow-lg': '0 20px 40px rgba(15,23,42,0.16)',
    },
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus UI',
    description: 'Primary colors, geometric contrast, and bold forms.',
    effects: { surface: 'bauhaus' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f8f5ee',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f3e9d7',
      '--color-text': '#1f2937',
      '--color-muted': '#4b5563',
      '--color-primary': '#ef4444',
      '--color-secondary': '#2563eb',
      '--color-accent': '#facc15',
      '--color-border': '#111827',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--border-width': '2px',
      '--radius-sm': '0.3rem',
      '--radius-md': '0.6rem',
      '--radius-lg': '0.9rem',
      '--shadow-sm': '4px 4px 0 #111827',
      '--shadow-md': '8px 8px 0 #111827',
      '--shadow-lg': '12px 12px 0 #111827',
    },
  },
  {
    id: 'retro-vintage',
    name: 'Retro / Vintage UI',
    description: 'Warm palettes and nostalgic textures.',
    effects: { surface: 'retro' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f7efe0',
      '--color-surface': '#fef6e6',
      '--color-surface-2': '#f2dcc2',
      '--color-text': '#4b2f1c',
      '--color-muted': '#8a5a3b',
      '--color-primary': '#d97706',
      '--color-secondary': '#0f766e',
      '--color-accent': '#b45309',
      '--color-border': '#d6b48b',
      '--color-on-primary': '#2b160b',
      '--color-on-secondary': '#ecfeff',
      '--shadow-sm': '0 8px 16px rgba(75,47,28,0.12)',
      '--shadow-md': '0 14px 26px rgba(75,47,28,0.18)',
      '--shadow-lg': '0 20px 38px rgba(75,47,28,0.22)',
      '--bg-pattern': 'linear-gradient(90deg, rgba(139,94,60,0.08), transparent 35%)',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk UI',
    description: 'Neon contrast and futuristic energy.',
    effects: { surface: 'cyber' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0b0f1a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#e0f2fe',
      '--color-muted': '#94a3b8',
      '--color-primary': '#22d3ee',
      '--color-secondary': '#f43f5e',
      '--color-accent': '#a855f7',
      '--color-border': '#334155',
      '--color-on-primary': '#051923',
      '--color-on-secondary': '#2d0b16',
      '--shadow-sm': '0 10px 28px rgba(34,211,238,0.2)',
      '--shadow-md': '0 16px 40px rgba(244,63,94,0.22)',
      '--shadow-lg': '0 24px 60px rgba(168,85,247,0.24)',
      '--bg-pattern': 'linear-gradient(135deg, rgba(34,211,238,0.12), transparent 40%), linear-gradient(225deg, rgba(244,63,94,0.12), transparent 40%)',
    },
  },
  {
    id: 'y2k',
    name: 'Y2K UI',
    description: 'Glossy gradients with bold pop accents.',
    effects: { surface: 'y2k' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f5f2ff',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#e8e4ff',
      '--color-text': '#2b1b47',
      '--color-muted': '#6b4ca5',
      '--color-primary': '#8b5cf6',
      '--color-secondary': '#22d3ee',
      '--color-accent': '#f472b6',
      '--color-border': '#d8ccff',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#0b1c24',
      '--shadow-sm': '0 10px 24px rgba(139,92,246,0.18)',
      '--shadow-md': '0 16px 34px rgba(34,211,238,0.18)',
      '--shadow-lg': '0 22px 50px rgba(244,114,182,0.2)',
      '--bg-pattern': 'radial-gradient(circle at top left, rgba(139,92,246,0.15), transparent 40%)',
    },
  },
  {
    id: 'pixel-8bit',
    name: 'Pixel / 8-bit UI',
    description: 'Chunky pixels and retro game nostalgia.',
    effects: { surface: 'pixel' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--font-sans': "'Courier New', ui-monospace, SFMono-Regular, Menlo, monospace",
      '--color-bg': '#0b1020',
      '--color-surface': '#1f2937',
      '--color-surface-2': '#243447',
      '--color-text': '#e5e7eb',
      '--color-muted': '#9ca3af',
      '--color-primary': '#34d399',
      '--color-secondary': '#fbbf24',
      '--color-accent': '#60a5fa',
      '--color-border': '#374151',
      '--color-on-primary': '#0b1020',
      '--color-on-secondary': '#2b1d06',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--shadow-sm': '0 6px 0 rgba(0,0,0,0.35)',
      '--shadow-md': '0 10px 0 rgba(0,0,0,0.45)',
      '--shadow-lg': '0 14px 0 rgba(0,0,0,0.55)',
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome UI',
    description: 'Single-hue elegance with minimal contrast shifts.',
    effects: { surface: 'mono' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f5f5f5',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#ededed',
      '--color-text': '#111111',
      '--color-muted': '#555555',
      '--color-primary': '#222222',
      '--color-secondary': '#444444',
      '--color-accent': '#000000',
      '--color-border': '#d4d4d4',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--shadow-sm': '0 8px 20px rgba(17,17,17,0.08)',
      '--shadow-md': '0 12px 28px rgba(17,17,17,0.12)',
      '--shadow-lg': '0 18px 36px rgba(17,17,17,0.16)',
    },
  },
  {
    id: 'illustrative',
    name: 'Illustrative UI',
    description: 'Soft, playful surfaces with storybook warmth.',
    effects: { surface: 'illustrative' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#fff7ed',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#ffe9d6',
      '--color-text': '#3b2f2a',
      '--color-muted': '#7c5f52',
      '--color-primary': '#fb923c',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#f59e0b',
      '--color-border': '#f2c9a8',
      '--color-on-primary': '#2a160d',
      '--color-on-secondary': '#0b1e2d',
      '--shadow-sm': '0 12px 26px rgba(251,146,60,0.18)',
      '--shadow-md': '0 18px 32px rgba(56,189,248,0.18)',
      '--shadow-lg': '0 26px 44px rgba(245,158,11,0.18)',
      '--bg-pattern': 'radial-gradient(circle at 15% 20%, rgba(251,146,60,0.2), transparent 45%), radial-gradient(circle at 80% 30%, rgba(56,189,248,0.18), transparent 45%)',
    },
  },
  {
    id: 'typographic-first',
    name: 'Typographic-First UI',
    description: 'Hierarchy-led layouts with bold type scale.',
    effects: { surface: 'type' },
    tokens: {
      ...baseTokens,
      '--font-size-xs': '0.875rem',
      '--font-size-sm': '1rem',
      '--font-size-md': '1.125rem',
      '--font-size-lg': '1.5rem',
      '--font-size-xl': '2rem',
      '--font-size-2xl': '2.75rem',
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f5f9',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#0f172a',
      '--color-secondary': '#64748b',
      '--color-accent': '#2563eb',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#0f172a',
    },
  },
  {
    id: 'skeuo-hybrid',
    name: 'Skeuomorphic Hybrid UI',
    description: 'Modern surfaces with subtle tactile depth.',
    effects: { surface: 'skeuo' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#1f1a17',
      '--color-surface': '#3b3027',
      '--color-surface-2': '#4b3b2f',
      '--color-text': '#f7e9d7',
      '--color-muted': '#c7b299',
      '--color-primary': '#d97706',
      '--color-secondary': '#65a30d',
      '--color-accent': '#f59e0b',
      '--color-border': '#6b4f3a',
      '--color-on-primary': '#23170f',
      '--color-on-secondary': '#13210a',
      '--shadow-sm': 'inset 0 1px 0 rgba(255,255,255,0.22), 0 8px 18px rgba(0,0,0,0.35)',
      '--shadow-md': 'inset 0 2px 0 rgba(255,255,255,0.2), 0 14px 26px rgba(0,0,0,0.45)',
      '--shadow-lg': 'inset 0 3px 0 rgba(255,255,255,0.18), 0 22px 36px rgba(0,0,0,0.55)',
    },
  },
  {
    id: 'conversational',
    name: 'Conversational UI',
    description: 'Friendly chat-inspired layout and warmth.',
    effects: { surface: 'conversational' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f5f7ff',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#eef2ff',
      '--color-text': '#1f2a44',
      '--color-muted': '#5b6c9b',
      '--color-primary': '#6366f1',
      '--color-secondary': '#22c55e',
      '--color-accent': '#38bdf8',
      '--color-border': '#dbe2ff',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#052e16',
      '--shadow-sm': '0 10px 24px rgba(99,102,241,0.18)',
      '--shadow-md': '0 16px 30px rgba(56,189,248,0.2)',
      '--shadow-lg': '0 22px 38px rgba(34,197,94,0.18)',
    },
  },
  {
    id: 'voice-oriented',
    name: 'Voice-Oriented UI',
    description: 'Large type, clear contrast, voice-ready focus.',
    effects: { surface: 'voice' },
    tokens: {
      ...baseTokens,
      ...accessibilityType,
      '--color-bg': '#0f172a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#cbd5f5',
      '--color-primary': '#38bdf8',
      '--color-secondary': '#a78bfa',
      '--color-accent': '#f59e0b',
      '--color-border': '#475569',
      '--color-on-primary': '#0b1120',
      '--color-on-secondary': '#0b1120',
      '--border-width': '2px',
    },
  },
  {
    id: 'gesture-based',
    name: 'Gesture-Based UI',
    description: 'Big touch targets and airy spacing.',
    effects: { surface: 'gesture' },
    tokens: {
      ...baseTokens,
      ...spaciousSpacing,
      '--color-bg': '#f0f9ff',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#e0f2fe',
      '--color-text': '#0f172a',
      '--color-muted': '#4b5563',
      '--color-primary': '#0ea5e9',
      '--color-secondary': '#22c55e',
      '--color-accent': '#f97316',
      '--color-border': '#bae6fd',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#052e16',
      '--radius-sm': '0.8rem',
      '--radius-md': '1.1rem',
      '--radius-lg': '1.6rem',
    },
  },
  {
    id: 'keyboard-first',
    name: 'Keyboard-First UI',
    description: 'Sharp focus states and command-friendly contrast.',
    effects: { surface: 'keyboard' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--color-bg': '#0b1020',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#cbd5f5',
      '--color-primary': '#22c55e',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#f59e0b',
      '--color-border': '#334155',
      '--color-on-primary': '#052e16',
      '--color-on-secondary': '#0b1120',
      '--border-width': '2px',
    },
  },
  {
    id: 'cli',
    name: 'Command-Line Inspired UI',
    description: 'Terminal-inspired monochrome contrast.',
    effects: { surface: 'cli' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--font-sans': "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
      '--color-bg': '#0a0f0d',
      '--color-surface': '#101915',
      '--color-surface-2': '#14211b',
      '--color-text': '#d1fae5',
      '--color-muted': '#6ee7b7',
      '--color-primary': '#22c55e',
      '--color-secondary': '#4ade80',
      '--color-accent': '#86efac',
      '--color-border': '#1f2f27',
      '--color-on-primary': '#052e16',
      '--color-on-secondary': '#052e16',
      '--radius-sm': '0.2rem',
      '--radius-md': '0.3rem',
      '--radius-lg': '0.4rem',
      '--shadow-sm': '0 6px 0 rgba(0,0,0,0.4)',
      '--shadow-md': '0 10px 0 rgba(0,0,0,0.5)',
      '--shadow-lg': '0 14px 0 rgba(0,0,0,0.6)',
    },
  },
  {
    id: 'dashboard-centric',
    name: 'Dashboard-Centric UI',
    description: 'Data tiles, dense navigation, and analytics focus.',
    effects: { surface: 'dashboard' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--layout-max': '1400px',
      '--color-bg': '#0f172a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#9ca3af',
      '--color-primary': '#38bdf8',
      '--color-secondary': '#a78bfa',
      '--color-accent': '#22c55e',
      '--color-border': '#334155',
      '--color-on-primary': '#0b1120',
      '--color-on-secondary': '#0b1120',
      '--shadow-sm': '0 10px 24px rgba(2,6,23,0.45)',
      '--shadow-md': '0 16px 30px rgba(2,6,23,0.5)',
      '--shadow-lg': '0 24px 40px rgba(2,6,23,0.55)',
    },
  },
  {
    id: 'card-modular',
    name: 'Card-Based Modular UI',
    description: 'Layered cards and modular layout rhythm.',
    effects: { surface: 'modular' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f5f9',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#6366f1',
      '--color-secondary': '#14b8a6',
      '--color-accent': '#f97316',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--radius-sm': '0.8rem',
      '--radius-md': '1rem',
      '--radius-lg': '1.4rem',
      '--shadow-sm': '0 12px 28px rgba(15,23,42,0.1)',
      '--shadow-md': '0 18px 36px rgba(15,23,42,0.14)',
      '--shadow-lg': '0 26px 48px rgba(15,23,42,0.18)',
    },
  },
  {
    id: 'timeline-based',
    name: 'Timeline-Based UI',
    description: 'Progressive flow and sequential emphasis.',
    effects: { surface: 'timeline' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f1f5f9',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#e2e8f0',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#0ea5e9',
      '--color-secondary': '#8b5cf6',
      '--color-accent': '#f97316',
      '--color-border': '#cbd5f5',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--shadow-sm': '0 8px 18px rgba(14,165,233,0.16)',
      '--shadow-md': '0 12px 26px rgba(139,92,246,0.18)',
      '--shadow-lg': '0 20px 34px rgba(249,115,22,0.18)',
    },
  },
  {
    id: 'wizard-steps',
    name: 'Wizard / Step-Based UI',
    description: 'Guided flow with clear progression.',
    effects: { surface: 'wizard' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#eef2ff',
      '--color-text': '#111827',
      '--color-muted': '#475569',
      '--color-primary': '#6366f1',
      '--color-secondary': '#22c55e',
      '--color-accent': '#f59e0b',
      '--color-border': '#e0e7ff',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#052e16',
      '--radius-sm': '0.6rem',
      '--radius-md': '0.9rem',
      '--radius-lg': '1.2rem',
    },
  },
  {
    id: 'single-screen',
    name: 'Single-Page / One-Screen UI',
    description: 'Focused layout with constrained canvas.',
    effects: { surface: 'single' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--layout-max': '980px',
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f5f9',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#0ea5e9',
      '--color-secondary': '#6366f1',
      '--color-accent': '#22c55e',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
    },
  },
  {
    id: 'wearable',
    name: 'Wearable UI',
    description: 'Compact UI with high clarity and touchable controls.',
    effects: { surface: 'wearable' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--layout-max': '760px',
      '--color-bg': '#0f172a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#94a3b8',
      '--color-primary': '#22c55e',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#f59e0b',
      '--color-border': '#334155',
      '--color-on-primary': '#052e16',
      '--color-on-secondary': '#0b1120',
      '--radius-sm': '0.7rem',
      '--radius-md': '1rem',
      '--radius-lg': '1.4rem',
    },
  },
  {
    id: 'tv-10foot',
    name: 'TV / 10-Foot UI',
    description: 'Large type and high contrast for distance viewing.',
    effects: { surface: 'tv' },
    tokens: {
      ...baseTokens,
      '--font-size-xs': '1rem',
      '--font-size-sm': '1.25rem',
      '--font-size-md': '1.5rem',
      '--font-size-lg': '2rem',
      '--font-size-xl': '2.5rem',
      '--font-size-2xl': '3.25rem',
      '--color-bg': '#0b1120',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#cbd5f5',
      '--color-primary': '#38bdf8',
      '--color-secondary': '#f59e0b',
      '--color-accent': '#a78bfa',
      '--color-border': '#334155',
      '--color-on-primary': '#0b1120',
      '--color-on-secondary': '#1f2937',
      '--radius-sm': '1rem',
      '--radius-md': '1.4rem',
      '--radius-lg': '1.8rem',
    },
  },
  {
    id: 'automotive',
    name: 'Automotive / In-Car UI',
    description: 'Contrast-forward, glanceable, and sharp.',
    effects: { surface: 'auto' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0b0f1a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f9fafb',
      '--color-muted': '#cbd5f5',
      '--color-primary': '#f97316',
      '--color-secondary': '#22d3ee',
      '--color-accent': '#f59e0b',
      '--color-border': '#334155',
      '--color-on-primary': '#1b0b05',
      '--color-on-secondary': '#0b1120',
      '--border-width': '2px',
      '--shadow-sm': '0 10px 26px rgba(2,6,23,0.45)',
      '--shadow-md': '0 16px 36px rgba(2,6,23,0.55)',
      '--shadow-lg': '0 24px 48px rgba(2,6,23,0.6)',
    },
  },
  {
    id: 'ar-ui',
    name: 'Augmented Reality (AR) UI',
    description: 'Translucent overlays with luminous accents.',
    effects: { surface: 'ar' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0a1224',
      '--color-surface': 'rgba(255,255,255,0.14)',
      '--color-surface-2': 'rgba(255,255,255,0.18)',
      '--color-text': '#e0f2fe',
      '--color-muted': '#b8c6ff',
      '--color-primary': '#22d3ee',
      '--color-secondary': '#a78bfa',
      '--color-accent': '#38bdf8',
      '--color-border': 'rgba(255,255,255,0.24)',
      '--color-on-primary': '#0a1224',
      '--color-on-secondary': '#0a1224',
      '--blur-amount': '16px',
      '--glass-bg': 'rgba(255,255,255,0.22)',
      '--shadow-sm': '0 12px 30px rgba(8,16,40,0.35)',
      '--shadow-md': '0 18px 42px rgba(8,16,40,0.45)',
      '--shadow-lg': '0 28px 60px rgba(8,16,40,0.55)',
    },
  },
  {
    id: 'vr-ui',
    name: 'Virtual Reality (VR) UI',
    description: 'Deep space canvases with floating UI cards.',
    effects: { surface: 'vr' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#050816',
      '--color-surface': '#101827',
      '--color-surface-2': '#1b2337',
      '--color-text': '#e2e8f0',
      '--color-muted': '#94a3b8',
      '--color-primary': '#38bdf8',
      '--color-secondary': '#f472b6',
      '--color-accent': '#fbbf24',
      '--color-border': '#2d3748',
      '--color-on-primary': '#05101a',
      '--color-on-secondary': '#1f2937',
      '--shadow-sm': '0 18px 40px rgba(2,6,23,0.55)',
      '--shadow-md': '0 28px 60px rgba(2,6,23,0.65)',
      '--shadow-lg': '0 40px 80px rgba(2,6,23,0.75)',
      '--card-tilt': 'rotateX(5deg) rotateY(4deg)',
      '--card-depth': '20px',
    },
  },
  {
    id: 'mr-ui',
    name: 'Mixed Reality (MR) UI',
    description: 'Hybrid spatial overlays with calm contrast.',
    effects: { surface: 'mr' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0d1324',
      '--color-surface': 'rgba(17,24,39,0.85)',
      '--color-surface-2': 'rgba(31,41,55,0.85)',
      '--color-text': '#e5e7eb',
      '--color-muted': '#cbd5f5',
      '--color-primary': '#22d3ee',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#a78bfa',
      '--color-border': 'rgba(148,163,184,0.4)',
      '--color-on-primary': '#0b1120',
      '--color-on-secondary': '#0b1120',
      '--shadow-sm': '0 16px 32px rgba(2,6,23,0.5)',
      '--shadow-md': '0 24px 46px rgba(2,6,23,0.6)',
      '--shadow-lg': '0 36px 64px rgba(2,6,23,0.7)',
    },
  },
  {
    id: 'data-dense',
    name: 'Data-Dense UI',
    description: 'Compact spacing and high information density.',
    effects: { surface: 'dense' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--font-size-xs': '0.7rem',
      '--font-size-sm': '0.8rem',
      '--font-size-md': '0.95rem',
      '--font-size-lg': '1.05rem',
      '--font-size-xl': '1.3rem',
      '--font-size-2xl': '1.6rem',
      '--color-bg': '#0f172a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#94a3b8',
      '--color-primary': '#22c55e',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#f59e0b',
      '--color-border': '#334155',
      '--color-on-primary': '#052e16',
      '--color-on-secondary': '#0b1120',
      '--border-width': '1px',
    },
  },
  {
    id: 'low-density',
    name: 'Low-Density / Calm UI',
    description: 'Spacious layout with soft visual cadence.',
    effects: { surface: 'calm' },
    tokens: {
      ...baseTokens,
      ...spaciousSpacing,
      '--color-bg': '#f9fafb',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#f1f5f9',
      '--color-text': '#0f172a',
      '--color-muted': '#64748b',
      '--color-primary': '#6366f1',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#a855f7',
      '--color-border': '#e2e8f0',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#0b1120',
      '--shadow-sm': '0 10px 22px rgba(99,102,241,0.1)',
      '--shadow-md': '0 16px 30px rgba(56,189,248,0.12)',
      '--shadow-lg': '0 22px 40px rgba(168,85,247,0.14)',
    },
  },
  {
    id: 'visualization-first',
    name: 'Visualization-First UI',
    description: 'Chart-focused contrast with vivid accents.',
    effects: { surface: 'viz' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0b1120',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#9ca3af',
      '--color-primary': '#22d3ee',
      '--color-secondary': '#f59e0b',
      '--color-accent': '#a78bfa',
      '--color-border': '#334155',
      '--color-on-primary': '#0b1120',
      '--color-on-secondary': '#1f2937',
      '--shadow-sm': '0 12px 30px rgba(34,211,238,0.2)',
      '--shadow-md': '0 18px 40px rgba(245,158,11,0.2)',
      '--shadow-lg': '0 26px 54px rgba(167,139,250,0.22)',
    },
  },
  {
    id: 'form-heavy',
    name: 'Form-Heavy UI',
    description: 'Focused on input clarity and consistent rhythm.',
    effects: { surface: 'form' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#eef2ff',
      '--color-text': '#111827',
      '--color-muted': '#475569',
      '--color-primary': '#2563eb',
      '--color-secondary': '#6366f1',
      '--color-accent': '#22c55e',
      '--color-border': '#c7d2fe',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#ffffff',
      '--radius-sm': '0.6rem',
      '--radius-md': '0.8rem',
      '--radius-lg': '1.1rem',
    },
  },
  {
    id: 'adaptive-context',
    name: 'Adaptive / Context-Aware UI',
    description: 'Balanced contrast with dynamic emphasis.',
    effects: { surface: 'adaptive-context' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#f1f5f9',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#e2e8f0',
      '--color-text': '#0f172a',
      '--color-muted': '#475569',
      '--color-primary': '#0ea5e9',
      '--color-secondary': '#22c55e',
      '--color-accent': '#a855f7',
      '--color-border': '#cbd5f5',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#052e16',
      '--shadow-sm': '0 8px 20px rgba(14,165,233,0.16)',
      '--shadow-md': '0 14px 28px rgba(34,197,94,0.16)',
      '--shadow-lg': '0 20px 36px rgba(168,85,247,0.18)',
    },
  },
  {
    id: 'predictive',
    name: 'Predictive UI',
    description: 'Forward-looking highlights and anticipatory accents.',
    effects: { surface: 'predictive' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0f172a',
      '--color-surface': '#111827',
      '--color-surface-2': '#1f2937',
      '--color-text': '#f8fafc',
      '--color-muted': '#cbd5f5',
      '--color-primary': '#a78bfa',
      '--color-secondary': '#38bdf8',
      '--color-accent': '#f59e0b',
      '--color-border': '#334155',
      '--color-on-primary': '#0b1120',
      '--color-on-secondary': '#0b1120',
      '--shadow-sm': '0 14px 28px rgba(167,139,250,0.22)',
      '--shadow-md': '0 20px 38px rgba(56,189,248,0.22)',
      '--shadow-lg': '0 28px 54px rgba(245,158,11,0.2)',
    },
  },
  {
    id: 'zero-ui',
    name: 'Zero-UI / Invisible UI',
    description: 'Minimal interface with near-invisible surfaces.',
    effects: { surface: 'zero' },
    tokens: {
      ...baseTokens,
      ...spaciousSpacing,
      '--color-bg': '#f9fafb',
      '--color-surface': 'rgba(255,255,255,0.4)',
      '--color-surface-2': 'rgba(255,255,255,0.6)',
      '--color-text': '#111827',
      '--color-muted': '#6b7280',
      '--color-primary': '#111827',
      '--color-secondary': '#9ca3af',
      '--color-accent': '#d1d5db',
      '--color-border': 'rgba(17,24,39,0.08)',
      '--color-on-primary': '#ffffff',
      '--color-on-secondary': '#111827',
      '--shadow-sm': '0 6px 18px rgba(15,23,42,0.06)',
      '--shadow-md': '0 10px 22px rgba(15,23,42,0.08)',
      '--shadow-lg': '0 14px 28px rgba(15,23,42,0.1)',
    },
  },
  {
    id: 'emotion-aware',
    name: 'Emotion-Aware UI',
    description: 'Warm gradients with soothing tones.',
    effects: { surface: 'emotion' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#fff7f3',
      '--color-surface': '#ffffff',
      '--color-surface-2': '#ffe5d6',
      '--color-text': '#3b2f2a',
      '--color-muted': '#7c5f52',
      '--color-primary': '#fb7185',
      '--color-secondary': '#f97316',
      '--color-accent': '#38bdf8',
      '--color-border': '#f2c9a8',
      '--color-on-primary': '#2a160d',
      '--color-on-secondary': '#2a160d',
      '--shadow-sm': '0 10px 24px rgba(251,113,133,0.16)',
      '--shadow-md': '0 16px 32px rgba(249,115,22,0.16)',
      '--shadow-lg': '0 24px 40px rgba(56,189,248,0.16)',
    },
  },
  {
    id: 'generative-composed',
    name: 'Generative / AI-Composed UI',
    description: 'Algorithmic gradients with vivid compositional layers.',
    effects: { surface: 'generative' },
    tokens: {
      ...baseTokens,
      '--color-bg': '#0a0f1f',
      '--color-surface': '#151b31',
      '--color-surface-2': '#1d2542',
      '--color-text': '#e0e7ff',
      '--color-muted': '#c7d2fe',
      '--color-primary': '#7c3aed',
      '--color-secondary': '#22d3ee',
      '--color-accent': '#f97316',
      '--color-border': '#2b3561',
      '--color-on-primary': '#0b1022',
      '--color-on-secondary': '#0b1120',
      '--shadow-sm': '0 12px 30px rgba(124,58,237,0.24)',
      '--shadow-md': '0 18px 44px rgba(34,211,238,0.22)',
      '--shadow-lg': '0 28px 68px rgba(249,115,22,0.2)',
      '--bg-pattern': 'radial-gradient(circle at 20% 20%, rgba(124,58,237,0.2), transparent 40%), radial-gradient(circle at 80% 30%, rgba(34,211,238,0.2), transparent 40%), radial-gradient(circle at 30% 80%, rgba(249,115,22,0.18), transparent 45%)',
    },
  },
  {
    id: 'liquid-glass',
    name: 'Liquid Glass UI',
    description: 'Fluid, elastic glass layers with refractive glow.',
    effects: { surface: 'liquid-glass' },
    tokens: {
      ...baseTokens,
      ...compactSpacing,
      '--color-bg': '#0a1224',
      '--color-surface': 'rgba(255,255,255,0.14)',
      '--color-surface-2': 'rgba(255,255,255,0.18)',
      '--color-text': '#e8f4ff',
      '--color-muted': '#bcd1ff',
      '--color-primary': '#7dd3fc',
      '--color-secondary': '#a78bfa',
      '--color-accent': '#22d3ee',
      '--color-border': 'rgba(255,255,255,0.25)',
      '--color-on-primary': '#0a1224',
      '--color-on-secondary': '#0a1224',
      '--shadow-sm': '0 12px 30px rgba(8,16,40,0.35)',
      '--shadow-md': '0 20px 44px rgba(8,16,40,0.45)',
      '--shadow-lg': '0 30px 68px rgba(8,16,40,0.55)',
      '--blur-amount': '22px',
      '--glass-bg': 'rgba(255, 255, 255, 0.22)',
      '--liquid-blur': '26px',
      '--liquid-glow': '0 0 40px rgba(34, 211, 238, 0.35)',
      '--liquid-flow-1': 'rgba(125, 211, 252, 0.45)',
      '--liquid-flow-2': 'rgba(167, 139, 250, 0.4)',
      '--liquid-flow-3': 'rgba(34, 211, 238, 0.35)',
      '--motion-soft': '28',
      '--bg-pattern': 'radial-gradient(circle at 20% 20%, rgba(125,211,252,0.28), transparent 45%), radial-gradient(circle at 80% 20%, rgba(167,139,250,0.24), transparent 45%), radial-gradient(circle at 50% 80%, rgba(34,211,238,0.2), transparent 50%)',
    },
  },
]

export const themeMap = themes.reduce((acc, theme) => {
  acc[theme.id] = theme
  return acc
}, {})

export const defaultThemeId = 'glassmorphism'
